### PR TITLE
Viewi 2 for CodeIgniter4

### PR DESCRIPTION
**Pull request by ivanvoitovych**
# CodeIgniter4 Viewi Demo

> Viewi allows you to create reactive web applications using your favorite PHP. It converts your code into native javascript code to run it in the browser. This way, you get a perfectly rendered HTML page on the first load, and at the same time, your page will remain reactive without requesting each next page on link clicks, etc.
https://viewi.net/

```console
$ git clone https://github.com/kenjis/ci4-viewi-demo.git
$ cd ci4-viewi-demo/
$ composer install
```

Assuming you have done composer install/update.

In first terminal:

`cd app/ViewiApp/js/`

Install NPM packages, if you are running for the first time:

`npm install`

Run watch mode:

`npm run watch`

In second terminal:

```console
php spark serve
```

Navigate to <http://localhost:8080/>.

### CODE REVIEW

**Comment by ivanvoitovych** [comment]
Hello @kenjis :)

Fresh update for CI4 with upgraded version of Viewi.

Please feel free to make changes.

Thank you!

**Comment by kenjis** [comment]
Thank you! But this does not work.

```
TypeError
Cannot assign int to property Viewi\App::$meta of type array
VENDORPATH/viewi/viewi/src/Viewi/App.php at line 86
```

**Comment by ivanvoitovych** [comment]
> Thank you! But this does not work.
> 
> ```
> TypeError
> Cannot assign int to property Viewi\App::$meta of type array
> VENDORPATH/viewi/viewi/src/Viewi/App.php at line 86
> ```

Oops 😬, will check it out

**Comment by kenjis** [comment]
Sorry, I did not run `npm install`!
Worked!!

**Comment by ivanvoitovych** [comment]
> Sorry, I did not run `npm install`! Worked!!

😅 Glad to hear it 😌

Soon I will drop some more changes, new version of Viewi will have some breaking changes and I will need to update multiple repos simultaneously 🥲

**Comment by kenjis** [comment]
Frankly, the differences are too large to understand, but since it worked, 
I'll merge it for the time being.

**Review by kenjis — APPROVED** [review]

**Pull request merged**
